// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermisoSystem.Data;

namespace PermisoSystem.Api.Migrations
{
    [DbContext(typeof(PermisoSystemContext))]
    [Migration("20211220211356_20211220_Initial")]
    partial class _20211220_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PermisoSystem.Data.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidosEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPermisoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("Permiso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidosEmpleado = "Ruiz",
                            FechaPermiso = new DateTime(2021, 12, 20, 14, 13, 55, 577, DateTimeKind.Local).AddTicks(6239),
                            NombreEmpleado = "Wildo",
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApellidosEmpleado = "Ruiz",
                            FechaPermiso = new DateTime(2021, 12, 20, 14, 13, 55, 578, DateTimeKind.Local).AddTicks(9343),
                            NombreEmpleado = "Carolina",
                            TipoPermisoId = 1
                        });
                });

            modelBuilder.Entity("PermisoSystem.Data.Entities.TipoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPermiso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Enfermedad"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Diligencias"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Otros"
                        });
                });

            modelBuilder.Entity("PermisoSystem.Data.Entities.Permiso", b =>
                {
                    b.HasOne("PermisoSystem.Data.Entities.TipoPermiso", "TipoPermiso")
                        .WithMany()
                        .HasForeignKey("TipoPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
